// Generate flows/strategy-build.json (the scene-3 build fixture) FROM
// flows/complete-strategy.json (your app export). DERIVED artifact — never
// hand-edit it. Edit CONFIG in scripts/lib/build-flow.js, then run:
//
//   npm run gen:build      (just the fixture)
//   npm run gen            (fixture + pipeline scene 3 — keep them in sync)
//
// Strategy edges are omitted from the fixture (they're drawn on camera by
// scene-3 `drag` events); only edges among the "base" nodes are baked in.

import { writeFileSync, mkdirSync } from 'fs';
import path from 'node:path';
import { buildFlow, getStrategy, ROOT, nameOf, portName } from './lib/build-flow.js';

const CONFIG = getStrategy(process.argv[2] || process.env.STRATEGY || 'ema');
const { nodes, baked, dragged } = buildFlow(CONFIG);

const outAbs = path.resolve(ROOT, CONFIG.out);
mkdirSync(path.dirname(outAbs), { recursive: true });
writeFileSync(outAbs, JSON.stringify({
  _comment: `GENERATED by scripts/gen-build.js from ${CONFIG.src} — do not edit by hand. Strategy edges are omitted (drawn on camera by scene-3 drag events).`,
  nodes, edges: baked,
}, null, 2));

console.log(`generated ${CONFIG.out}`);
console.log('build order (nodeCount = id):');
nodes.forEach((n, i) => console.log(`  ${i + 1}  ${n.data.nodeKey.padEnd(12)} ${n.data.Name}`));
console.log(`\nbaked base edges: ${baked.length}`);
console.log('drag edges (wired on camera by scene 3):');
dragged.forEach((e) => console.log(
  `  ${nameOf(nodes, e.source)}.${portName(nodes, e.source, e.sourceHandle, 'out')} -> ${nameOf(nodes, e.target)}.${portName(nodes, e.target, e.targetHandle, 'in')}` +
  `   [#${e.source} ${e.sourceHandle} -> #${e.target} ${e.targetHandle}]`));
